site_name: Open To Close API Python Client
site_description: Python wrapper for the Open To Close API - Manage properties, agents, contacts, and more
site_url: https://theperrygroup.github.io/open-to-close
repo_url: https://github.com/theperrygroup/open-to-close
repo_name: theperrygroup/open-to-close

# Copyright
copyright: Copyright &copy; 2024 The Perry Group

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - announce.dismiss

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: theperrygroup
      repo: open-to-close
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Authentication: getting-started/authentication.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - API Reference:
    - api/index.md
    - Main Client: api/client.md
    - Core Resources:
      - Properties: api/properties.md
      - Agents: api/agents.md
      - Contacts: api/contacts.md
      - Teams: api/teams.md
      - Users: api/users.md
      - Tags: api/tags.md
    - Property Sub-Resources:
      - Property Contacts: api/property-contacts.md
      - Property Documents: api/property-documents.md
      - Property Emails: api/property-emails.md
      - Property Notes: api/property-notes.md
      - Property Tasks: api/property-tasks.md
  - Guides:
    - guides/index.md
    - Error Handling: guides/error-handling.md
    - Best Practices: guides/best-practices.md
    - Examples: guides/examples.md
    - Integration Patterns: guides/integration-patterns.md
  - Reference:
    - reference/index.md
    - Exceptions: reference/exceptions.md
    - Data Types: reference/data-types.md
    - Rate Limits: reference/rate-limits.md
    - Changelog: reference/changelog.md


# Extra
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theperrygroup/open-to-close
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/open-to-close/
  generator: false

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 